# Generated by Django 5.2.4 on 2025-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow'), ('Pink', 'Pink')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flower_type',
            field=models.CharField(blank=True, choices=[('Roses', 'Roses'), ('Lilies', 'Lilies'), ('Tulips', 'Tulips'), ('Orchids', 'Orchids')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Anniversary', 'Anniversary'), ('Valentine', 'Valentine')], max_length=50, null=True),
        ),
    ]
