# Generated by Django 5.2.4 on 2025-08-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_color_product_flower_type_product_occasion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
