# Generated by Django 5.2.4 on 2025-08-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flower_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
    ]
