# Generated by Django 5.2.4 on 2025-08-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
